#!/bin/bash

# =============================================================================
# setup-claude-accounts.sh
# Switch between multiple Claude Code accounts without logging in/out
# Supports 2 or 3 accounts
#
# Author: Juliana Miller (https://github.com/Julianamiller)
# License: MIT
# =============================================================================

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
BOLD='\033[1m'
RESET='\033[0m'

info()  { echo -e "${GREEN}[✓]${RESET} $1"; }
warn()  { echo -e "${YELLOW}[!]${RESET} $1"; }
step()  { echo -e "\n${BOLD}━━━ $1 ━━━${RESET}"; }
error() { echo -e "${RED}[✗]${RESET} $1"; exit 1; }
ask()   { echo -e "${BLUE}[?]${RESET} $1"; }

MARKER="$HOME/.claude_current"

# -----------------------------------------------------------------------------
# Dependencies
# -----------------------------------------------------------------------------

step "Checking dependencies"

command -v claude &>/dev/null || error "Claude Code not found. Install it at: https://claude.ai/download"
command -v rsync  &>/dev/null || error "rsync not found. Install with: brew install rsync"

info "Claude Code and rsync OK"

if [ -f "$HOME/.zshrc" ]; then
  SHELL_RC="$HOME/.zshrc"
elif [ -f "$HOME/.bashrc" ]; then
  SHELL_RC="$HOME/.bashrc"
else
  error "No ~/.zshrc or ~/.bashrc found."
fi

info "Shell config: $SHELL_RC"

# -----------------------------------------------------------------------------
# How many accounts?
# -----------------------------------------------------------------------------

step "Setup"

ask "How many accounts do you want to configure? (2 or 3)"
read -r NUM_ACCOUNTS

if [[ "$NUM_ACCOUNTS" != "2" && "$NUM_ACCOUNTS" != "3" ]]; then
  error "Please enter 2 or 3."
fi

ask "Name for account 1 (e.g. personal):"
read -r ACCOUNT_1
ask "Name for account 2 (e.g. work):"
read -r ACCOUNT_2

if [[ "$NUM_ACCOUNTS" == "3" ]]; then
  ask "Name for account 3 (e.g. freelance):"
  read -r ACCOUNT_3
fi

# Validate names
for name in "$ACCOUNT_1" "$ACCOUNT_2" ${ACCOUNT_3:+"$ACCOUNT_3"}; do
  if [[ ! "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    error "Account names must contain only letters, numbers, hyphens, or underscores. Got: '$name'"
  fi
done

echo ""
info "Accounts: $ACCOUNT_1, $ACCOUNT_2${ACCOUNT_3:+, $ACCOUNT_3}"

# Check if already configured
if grep -q "claude-switch" "$SHELL_RC" 2>/dev/null; then
  warn "Aliases already exist in $SHELL_RC. Skipping alias setup."
  ALIASES_EXIST=true
else
  ALIASES_EXIST=false
fi

# -----------------------------------------------------------------------------
# Login and save each account
# -----------------------------------------------------------------------------

save_account() {
  local name="$1"
  local dir="$HOME/.claude_${name}"
  local json="$HOME/.claude_${name}.json"

  rsync -a --ignore-errors --delete "$HOME/.claude/" "$dir/"
  cp "$HOME/.claude.json" "$json"
  info "Account '$name' saved to $dir"
}

login_and_save() {
  local step_num="$1"
  local name="$2"

  step "STEP $step_num — Account: $name"
  echo "Log in with your '$name' account."
  echo "Press ENTER to open the login flow..."
  read -r

  claude auth login

  echo ""
  echo "Saving account '$name'..."
  save_account "$name"
}

login_and_save 1 "$ACCOUNT_1"
login_and_save 2 "$ACCOUNT_2"
[[ "$NUM_ACCOUNTS" == "3" ]] && login_and_save 3 "$ACCOUNT_3"

# Mark the last account as active
echo "$ACCOUNT_2" > "$MARKER"
[[ "$NUM_ACCOUNTS" == "3" ]] && echo "$ACCOUNT_3" > "$MARKER"

# -----------------------------------------------------------------------------
# Generate switch function and aliases
# -----------------------------------------------------------------------------

step "Configuring aliases in $SHELL_RC"

if [[ "$ALIASES_EXIST" == false ]]; then

  ALL_ACCOUNTS="$ACCOUNT_1 $ACCOUNT_2${ACCOUNT_3:+ $ACCOUNT_3}"

  cat >> "$SHELL_RC" << SHELL_BLOCK

# Claude Code - multi-account switch
# Generated by setup-claude-accounts.sh

_claude_switch() {
  local target="\$1"
  local marker="\$HOME/.claude_current"
  local current="\$(cat "\$marker" 2>/dev/null)"
  local valid_accounts="$ALL_ACCOUNTS"

  if [[ -z "\$target" ]]; then
    echo "Usage: use-<account>"
    echo "Available accounts: $ALL_ACCOUNTS"
    return 1
  fi

  if [[ "\$target" == "\$current" ]]; then
    echo "Account '\$target' is already active."
    return 0
  fi

  # Save current state
  if [[ -n "\$current" ]]; then
    rsync -a --ignore-errors --delete "\$HOME/.claude/" "\$HOME/.claude_\${current}/" && \\
    cp "\$HOME/.claude.json" "\$HOME/.claude_\${current}.json"
    echo "Saved account '\$current'."
  fi

  # Restore target
  rsync -a --ignore-errors --delete "\$HOME/.claude_\${target}/" "\$HOME/.claude/" && \\
  cp "\$HOME/.claude_\${target}.json" "\$HOME/.claude.json"
  echo "\$target" > "\$marker"

  echo "Account '\$target' is now active. Restart VS Code to apply."
}

alias use-${ACCOUNT_1}='_claude_switch ${ACCOUNT_1}'
alias use-${ACCOUNT_2}='_claude_switch ${ACCOUNT_2}'
SHELL_BLOCK

  if [[ "$NUM_ACCOUNTS" == "3" ]]; then
    echo "alias use-${ACCOUNT_3}='_claude_switch ${ACCOUNT_3}'" >> "$SHELL_RC"
  fi

  info "Aliases added"
else
  warn "Aliases already existed — no changes made"
fi

# -----------------------------------------------------------------------------
# Done
# -----------------------------------------------------------------------------

step "All done!"
echo ""
echo "Reload your shell:"
echo -e "  ${BOLD}source $SHELL_RC${RESET}"
echo ""
echo "Then switch accounts with:"
echo -e "  ${BOLD}use-${ACCOUNT_1}${RESET}   → activate account '${ACCOUNT_1}'"
echo -e "  ${BOLD}use-${ACCOUNT_2}${RESET}   → activate account '${ACCOUNT_2}'"
[[ "$NUM_ACCOUNTS" == "3" ]] && echo -e "  ${BOLD}use-${ACCOUNT_3}${RESET}   → activate account '${ACCOUNT_3}'"
echo ""
warn "Always restart VS Code after switching accounts."
